apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passbolt-ingress
  namespace: passbolt
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - passbolt.local
    secretName: passbolt-tls-secret
  rules:
  - host: passbolt.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: passbolt-service
            port:
              number: 80

