prometheus: 
  prometheusSpec:
    retention: 24h
    resources: 
      requests:
        memory: 256Mi
      limits:
        memory: 512Mi
grafana:
  adminUser: admin
  adminPassword: admin # <--- This is a one-time password, change it after the first login
  persistence:
    enabled: true
    storageClassName: local-path
    size: 1Gi