apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: passbolt
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources: 
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: passbolt
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        env:
        - name: MARIADB_DATABASE
          value: "passbolt"
        - name: MARIADB_USER
          value: "passboltuser"
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passbolt-db-secrets
              key: mariadb-password
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passbolt-db-secrets
              key: mariadb-root-password
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: passbolt
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306