apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: passbolt-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fernandoalvear21/homelab-k3s'
    targetRevision: develop
    path: apps/passbolt
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: passbolt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
