global:
  domain: argocd.local

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: false

# RAM and CPU resources for the Argo CD server
controller:
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

redis:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi