apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: passbolt
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: mirror.gcr.io/library/nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: passbolt
spec:
  selector:
    app: web
  ports:
    - port: 80
